openapi: 3.0.3
info:
  title: Productive.io API – Timesheets   Bulk
  version: 2.0.0
paths:
  /api/v2/timesheets:
    delete:
      summary: Deletes timesheets DELETE
      operationId: deleteTimesheets
      tags:
      - Timesheets   Bulk
      parameters: []
      responses:
        '204':
          description: Deleted
        '404':
          description: Not found
